import Header from '@/components/Header/Header'
import Head from 'next/head'
import styles from "../styles/Home.module.scss"
import clsx from "clsx"
import Footer from '@/components/Footer/Footer'
import Revalution from '@/components/Revalution/Revalution'
import PlanTrips from '@/components/PlanTrips/PlanTrips'
import AboutFestival from '@/components/AboutFestival/AboutFestival'
import RevalutionFestival from '@/components/RevalutionFestival/RevalutionFestival'
import UpcomingFestival from '@/components/UpcomingFestival/UpcomingFestival'
import OurPreviousFestival from '@/components/OurPreviousFestival/OurPreviousFestival'
import Lifetime from '@/components/Lifetime/Lifetime'
export default function Home() {
  return (
    <>
      <Head>
        <title>Jol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ background: "#0A0A0A" }}>
        <div className={clsx("", styles.topBanner)}>

          <div className={clsx('container ', styles.containerWidth, styles.containerColor)}>
            <Header />
          </div>

          <div className={clsx("container", styles.containerWidth)}>
            <div style={{ marginTop: "60px" }} className='row justify-content-center'>
              <div className='col-lg-6 col-md-8 justify-content-center'>
                <div style={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
                  <img src='/assests/top-logo-rav/logo-rav-1.png' alt='logo-rav-1' />
                </div>


              </div>

              <div className='col-lg-7 col-md-10 justify-content-center'>
                <div style={{ marginTop: "130px" }}>
                  <h1 style={{ fontSize: "32px", fontWeight: "300", color: "rgba(255,255,255,0.7)", textAlign: "center" }}>Let's Party in Paradise!</h1>
                  <p className={clsx(styles.para1)} style={{ textAlign: "center", fontWeight: "bold", color: "#FFFFFF", fontSize: "50px" }}>The Next Big Music Festival is Coming to Vietnam!</p>
                  <img style={{ display: "block", margin: "auto", marginBottom: "60px" }} src='/assests/img-pink-line1.svg' alt='img-pink-line1' />
                </div>


              </div>
            </div>


          </div>
        </div>


        <div className={clsx("container", styles.containerWidth)}>
          <Revalution />
          <PlanTrips />




        </div>

        {/*about the festival    */}
        <section className={clsx(styles.aboutSectionDiv)}>
          <AboutFestival />
        </section>

        {/* ravalution festival  */}
        <section className={clsx(styles.ravalutionFestivalDiv)}>
          <RevalutionFestival />
        </section>

        {/* our upcoming festival */}
        <section className={clsx(styles.upcomingFestivalSection)}>
          <UpcomingFestival />
        </section>

        <section style={{ marginTop: "133px" }} className={clsx("container", styles.containerWidth)} >
          <OurPreviousFestival />
        </section>

        <section className={clsx(styles.lifetimeSection)} >
          <Lifetime />
        </section>

        {/* footer */}
        <div className={clsx("container", styles.containerWidth)} >
          <Footer />
        </div>
        <div style={{ background: "#1F1F1F", padding: "15px 0px" }} >
          <p style={{ textAlign: "center", fontSize: "14px", color: "rgba(255,255,255,0.5)", marginBottom: "0px" }}>@2020 Jol - All Rights Reserved</p>
        </div>
      </main>

    </>
  )
}
